module.exports = {
    apps: [
        ...[
            "automod",
            "autoresponder",
            "autoroles",
            "backend",
            "commander",
            "count",
            "custom-roles",
            "interactions",
            "logging",
            "modmail",
            "nukeguard",
            "reaction-roles-reactions",
            "reddit-feeds",
            "starboard",
            "stats-channels",
            "sticky-roles",
            "supporter-announcements",
            "task-runner",
            "tickets",
            "welcome",
            "xp",
        ].map((name) => ({
            name,
            cwd: `./packages/${name}`,
            script: "bun start",
        })),
        {
            name: "dashboard",
            cwd: "./packages/dashboard",
            script: "npm start",
        },
    ],
};
