import type { PremiumBenefits } from "./types";

export enum PremiumTier {
    FREE = 0,
    BASIC,
    ULTIMATE,
}

export const premiumBenefits: Record<PremiumTier, PremiumBenefits> = {
    [PremiumTier.FREE]: {
        name: "Free Tier",
        vanityClient: false,
        customizeXpBackgrounds: false,
        multiModmail: false,
        multiTickets: false,
        customizeTicketOpenMessage: false,
        supporterAnnouncementsCountLimit: 3,
        xpBonusChannelCountLimit: 10,
        xpBonusRoleCountLimit: 5,
        xpRewardCountLimit: 10,
        reactionRolesCountLimit: 10,
        purgeAtOnceLimit: 100,
        automodCountLimit: 10,
        statsChannelsCountLimit: 5,
        autoresponderCountLimit: 10,
        modmailTargetCountLimit: 1,
        ticketPromptCountLimit: 3,
        ticketTargetCountLimit: 1,
        redditFeedsCountLimit: 3,
        countCountLimit: 3,
    },
    [PremiumTier.BASIC]: {
        name: "Daedalus Premium (Basic)",
        vanityClient: false,
        customizeXpBackgrounds: true,
        multiModmail: false,
        multiTickets: true,
        customizeTicketOpenMessage: true,
        supporterAnnouncementsCountLimit: 10,
        xpBonusChannelCountLimit: 25,
        xpBonusRoleCountLimit: 20,
        xpRewardCountLimit: 25,
        reactionRolesCountLimit: 25,
        purgeAtOnceLimit: 500,
        automodCountLimit: 25,
        statsChannelsCountLimit: 10,
        autoresponderCountLimit: 25,
        modmailTargetCountLimit: 1,
        ticketPromptCountLimit: 6,
        ticketTargetCountLimit: 3,
        redditFeedsCountLimit: 6,
        countCountLimit: 6,
    },
    [PremiumTier.ULTIMATE]: {
        name: "Daedalus Premium (Ultimate)",
        vanityClient: true,
        customizeXpBackgrounds: true,
        multiModmail: true,
        multiTickets: true,
        customizeTicketOpenMessage: true,
        supporterAnnouncementsCountLimit: 25,
        xpBonusChannelCountLimit: 200,
        xpBonusRoleCountLimit: 200,
        xpRewardCountLimit: 200,
        reactionRolesCountLimit: 50,
        purgeAtOnceLimit: 2000,
        automodCountLimit: 50,
        statsChannelsCountLimit: 25,
        autoresponderCountLimit: 50,
        modmailTargetCountLimit: 5,
        ticketPromptCountLimit: 10,
        ticketTargetCountLimit: 10,
        redditFeedsCountLimit: 10,
        countCountLimit: 10,
    },
};
