import {
    FaArrowDownWideShort,
    FaArrowRotateRight,
    FaArrowUp91,
    FaBell,
    FaBolt,
    FaBroom,
    FaBullhorn,
    FaCalendarDay,
    FaChartLine,
    FaCircleInfo,
    FaCircleQuestion,
    FaClockRotateLeft,
    FaComment,
    FaComments,
    FaDeleteLeft,
    FaDoorOpen,
    FaEnvelope,
    FaEraser,
    FaEye,
    FaEyeDropper,
    FaEyeLowVision,
    FaFillDrip,
    FaFilter,
    FaFlag,
    FaGauge,
    FaGavel,
    FaGift,
    FaHandshake,
    FaHourglassStart,
    FaIcons,
    FaIdBadge,
    FaIdCard,
    FaListUl,
    FaLock,
    FaMedal,
    FaMoneyBillTransfer,
    FaNoteSticky,
    FaQrcode,
    FaRankingStar,
    FaReddit,
    FaReply,
    FaShieldHalved,
    FaShuffle,
    FaSnowflake,
    FaSquarePollVertical,
    FaStar,
    FaTag,
    FaTags,
    FaTicket,
    FaToolbox,
    FaTrash,
    FaTriangleExclamation,
    FaUserGear,
    FaUserMinus,
    FaUsersRays,
    FaVolumeLow,
    FaVolumeXmark,
    FaWandMagicSparkles,
} from "react-icons/fa6";
import { IconType } from "react-icons/lib";

export const moduleIcons: Record<string, IconType> = {
    logging: FaListUl,
    welcome: FaDoorOpen,
    "supporter-announcements": FaBullhorn,
    xp: FaRankingStar,
    "reaction-roles": FaIcons,
    moderation: FaShieldHalved,
    starboard: FaStar,
    automod: FaEye,
    autokick: FaFilter,
    "sticky-roles": FaArrowRotateRight,
    autoroles: FaBolt,
    "custom-roles": FaEyeDropper,
    "stats-channels": FaChartLine,
    autoresponder: FaReply,
    modmail: FaEnvelope,
    tickets: FaTicket,
    nukeguard: FaLock,
    suggestions: FaComment,
    "co-op": FaHandshake,
    "reddit-feeds": FaReddit,
    count: FaArrowUp91,
    giveaways: FaGift,
    reminders: FaCalendarDay,
    reports: FaFlag,
    polls: FaSquarePollVertical,
    highlights: FaBell,
    utility: FaToolbox,
    "sticky-messages": FaNoteSticky,
    fun: FaWandMagicSparkles,
};

export const commandIcons: Record<string, IconType> = {
    top: FaArrowDownWideShort,
    rank: FaMedal,
    xp: FaRankingStar,
    ban: FaGavel,
    kick: FaUserMinus,
    mute: FaVolumeXmark,
    timeout: FaHourglassStart,
    warn: FaTriangleExclamation,
    unban: FaUserGear,
    unmute: FaVolumeLow,
    massban: FaUsersRays,
    history: FaClockRotateLeft,
    "delete-history": FaDeleteLeft,
    "clear-history": FaBroom,
    slowmode: FaGauge,
    purge: FaTrash,
    notes: FaNoteSticky,
    role: FaFillDrip,
    modmail: FaEnvelope,
    ticket: FaTicket,
    suggest: FaComment,
    suggestion: FaComments,
    "co-op": FaHandshake,
    scoreboard: FaRankingStar,
    giveaway: FaGift,
    reminder: FaCalendarDay,
    "Report User": FaFlag,
    "Flag Message": FaFlag,
    report: FaFlag,
    flag: FaFlag,
    poll: FaSquarePollVertical,
    highlight: FaBell,
    help: FaCircleQuestion,
    info: FaCircleInfo,
    avatar: FaIdBadge,
    roles: FaUserGear,
    code: FaGift,
    qr: FaQrcode,
    convert: FaMoneyBillTransfer,
    snowflake: FaSnowflake,
    "role-accessibility": FaEyeLowVision,
    "Extract IDs": FaIdCard,
    stick: FaTag,
    unstick: FaEraser,
    sticklist: FaTags,
    random: FaShuffle,
};
