CREATE TABLE `guild_nukeguard_settings` (
	`guild` varchar(20) NOT NULL,
	`admin_channel` varchar(20),
	`ping_roles` text NOT NULL,
	`ping_here` boolean NOT NULL,
	`exempted_roles` text NOT NULL,
	`watch_channels_by_default` boolean NOT NULL,
	`ignored_channels` text NOT NULL,
	`watched_channels` text NOT NULL,
	`watch_roles_by_default` boolean NOT NULL,
	`ignored_roles` text NOT NULL,
	`watched_roles` text NOT NULL,
	`watch_emoji` boolean NOT NULL,
	`watch_stickers` boolean NOT NULL,
	`watch_sounds` boolean NOT NULL,
	`prevent_webhook_creation` boolean NOT NULL,
	`watch_webhook_deletion` boolean NOT NULL,
	`enable_ratelimit` boolean NOT NULL,
	`ratelimit_kicking` boolean NOT NULL,
	`ratelimit_threshold` int,
	`ratelimit_time` int,
	`restrict_roles_lenient` boolean NOT NULL,
	`restrict_roles_by_default` boolean NOT NULL,
	`restrict_roles_allowed_roles` text NOT NULL,
	`restrict_roles_blocked_roles` text NOT NULL,
	CONSTRAINT `guild_nukeguard_settings_guild` PRIMARY KEY(`guild`)
);
